name: Update Submodules

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-submodules:
    name: Update Submodules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update submodules on main branch with explicit pull strategy
        run: |
          git submodule foreach --recursive '
            git checkout main || (echo "Branch main não encontrada nesse submódulo" && exit 0);
            git pull origin main --allow-unrelated-histories --no-rebase;
          '

      - name: Commit and push changes
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update submodules"
            git push
          fi
